name: Comentar usu치rio do push

on:
  push:
    branches:
      - main

permissions:
  contents: write  # necess치rio para criar coment치rios em commits via GITHUB_TOKEN

jobs:
  comment-user:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do c칩digo # necess치rio para a칞칫es que interagem com o reposit칩rio
        uses: actions/checkout@v4 # fazer checkout do c칩digo

      - name: Comentar no commit quem fez o push # comentar no commit quem fez o push
        uses: actions/github-script@v6 # usar a칞칚o para comentar
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # token para autentica칞칚o 
          script: |
            const actor = context.actor;
            const sha = context.sha;
            const body = `游녦 O push foi feito por **${actor}**.`; 
            });
        
