# .github/workflows/create-readme.yml
name: Criar arquivo com informações do push

on:
  push:
    branches:
      - main

permissions:
  contents: write  # permite criar e commitar arquivos no repositório

jobs:
  create-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v4

      - name: Criar arquivo com informações
        run: |
          echo "👋 Este push foi feito por: ${{ github.actor }}" > readme.txt
          echo "📅 Data: $(date)" >> readme.txt
          echo "🔗 Commit: ${{ github.sha }}" >> readme.txt
          cat readme.txt

      - name: Commitar e enviar o arquivo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add readme.txt
          git commit -m "Adicionado arquivo automático com dados do push"
          git push
