name: Listar Arquivos

on: push

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # É crucial para acessar o código [15]

      - name: Listar arquivos
        run: |
          echo "### Listando arquivos com 'ls -R'"
          ls -R
